# File: pip-error.txt

# During a test run, the pathagar-setup.sh script failed during the 
# 'pip intall -r requirements.pip' command.  This file describes
# exactly what happened.
#
##### When this part began running:

echo ".. run pip install -r requirements.pip (takes a long time) ..."
if pip install -r requirements.pip
then
    echo "... finished installing requirements into the penv."
else
    echo "... pip install failed! Terminating!"
    exit 1
fi

#####  The part up to the failure and then the
#####  associated trace back is provided here: 


Collecting Django==1.4.5 (from -r requirements.pip (line 1))
  Downloading Django-1.4.5.tar.gz (7.7MB)
    100% |████████████████████████████████| 7.7MB 29kB/s 
Collecting django-tagging==0.3.1 (from -r requirements.pip (line 2))
  Downloading django-tagging-0.3.1.tar.gz
Collecting django-sendfile==0.3.6 (from -r requirements.pip (line 3))
  Downloading django-sendfile-0.3.6.tar.gz
Collecting MySQL-python>=1.2.3 (from -r requirements.pip (line 4))
  Downloading MySQL-python-1.2.5.zip (108kB)
    100% |████████████████████████████████| 112kB 154kB/s 
Collecting lxml==3.4.4 (from -r requirements.pip (line 5))
ption:
Traceback (most recent call last):
  File
"/home/pi/pathagar/penv/local/lib/python2.7/site-packages/pip/basecommand.py",
line 215, in main
    status = self.run(options, args)
  File
"/home/pi/pathagar/penv/local/lib/python2.7/site-packages/pip/commands/install.py",
line 353, in run
    wb.build(autobuilding=True)
  File
"/home/pi/pathagar/penv/local/lib/python2.7/site-packages/pip/wheel.py",
line 749, in build
    self.requirement_set.prepare_files(self.finder)
  File
"/home/pi/pathagar/penv/local/lib/python2.7/site-packages/pip/req/req_set.py",
line 380, in prepare_files
    ignore_dependencies=self.ignore_dependencies))
  File
"/home/pi/pathagar/penv/local/lib/python2.7/site-packages/pip/req/req_set.py",
line 554, in _prepare_file
    require_hashes
  File
"/home/pi/pathagar/penv/local/lib/python2.7/site-packages/pip/req/req_install.py",
line 278, in populate_link
    self.link = finder.find_requirement(self, upgrade)
  File
"/home/pi/pathagar/penv/local/lib/python2.7/site-packages/pip/index.py",
line 465, in find_requirement
    all_candidates = self.find_all_candidates(req.name)
  File
"/home/pi/pathagar/penv/local/lib/python2.7/site-packages/pip/index.py",
line 423, in find_all_candidates
    for page in self._get_pages(url_locations, project_name):
  File
"/home/pi/pathagar/penv/local/lib/python2.7/site-packages/pip/index.py",
line 568, in _get_pages
    page = self._get_page(location)
  File
"/home/pi/pathagar/penv/local/lib/python2.7/site-packages/pip/index.py",
line 683, in _get_page
    return HTMLPage.get_page(link, session=self.session)
  File
"/home/pi/pathagar/penv/local/lib/python2.7/site-packages/pip/index.py",
line 792, in get_page
    "Cache-Control": "max-age=600",
  File
"/home/pi/pathagar/penv/share/python-wheels/requests-2.12.4-py2.py3-none-any.whl/requests/sessions.py",
line 501, in get
    return self.request('GET', url, **kwargs)
  File
"/home/pi/pathagar/penv/local/lib/python2.7/site-packages/pip/download.py",
line 386, in request
    return super(PipSession, self).request(method, url, *args,
**kwargs)
  File
"/home/pi/pathagar/penv/share/python-wheels/requests-2.12.4-py2.py3-none-any.whl/requests/sessions.py",
line 488, in request
    resp = self.send(prep, **send_kwargs)
  File
"/home/pi/pathagar/penv/share/python-wheels/requests-2.12.4-py2.py3-none-any.whl/requests/sessions.py",
line 609, in send
    r = adapter.send(request, **kwargs)
  File
"/home/pi/pathagar/penv/share/python-wheels/CacheControl-0.11.7-py2.py3-none-any.whl/cachecontrol/adapter.py",
line 47, in send
    resp = super(CacheControlAdapter, self).send(request, **kw)
  File
"/home/pi/pathagar/penv/share/python-wheels/requests-2.12.4-py2.py3-none-any.whl/requests/adapters.py",
line 423, in send
    timeout=timeout
  File
"/home/pi/pathagar/penv/share/python-wheels/urllib3-1.19.1-py2.py3-none-any.whl/urllib3/connectionpool.py",
line 643, in urlopen
    _stacktrace=sys.exc_info()[2])
  File
"/home/pi/pathagar/penv/share/python-wheels/urllib3-1.19.1-py2.py3-none-any.whl/urllib3/util/retry.py",
line 315, in increment
    total -= 1
TypeError: unsupported operand type(s) for -=: 'Retry' and 'int'

##########################################################################

# I then reran the pip install command as seen below- and it
# completed successfully...

pi@pi-7:~/phInfo $ cd ../pathagar/
pi@pi-7:~/pathagar $ source penv/bin/activate
(penv) pi@pi-7:~/pathagar $ pip install -r requirements.pip
Collecting Django==1.4.5 (from -r requirements.pip (line 1))
  Using cached Django-1.4.5.tar.gz
Collecting django-tagging==0.3.1 (from -r requirements.pip (line 2))
  Using cached django-tagging-0.3.1.tar.gz
Collecting django-sendfile==0.3.6 (from -r requirements.pip (line 3))
  Using cached django-sendfile-0.3.6.tar.gz
Collecting MySQL-python>=1.2.3 (from -r requirements.pip (line 4))
  Using cached MySQL-python-1.2.5.zip
Collecting lxml==3.4.4 (from -r requirements.pip (line 5))
  Downloading lxml-3.4.4.tar.gz (3.5MB)
    100% |████████████████████████████████| 3.5MB 34kB/s 
Collecting django-taggit==0.14.0 (from -r requirements.pip (line 6))
  Downloading django_taggit-0.14.0-py2.py3-none-any.whl
Collecting Unidecode (from django-sendfile==0.3.6->-r requirements.pip
(line 3))
  Downloading Unidecode-0.04.21-py2.py3-none-any.whl (228kB)
    100% |████████████████████████████████| 235kB 79kB/s 
Building wheels for collected packages: Django, django-tagging,
django-sendfile, MySQL-python, lxml
  Running setup.py bdist_wheel for Django ... done
  Stored in directory:
/home/pi/.cache/pip/wheels/0d/49/64/d57b7648de653abe02c95b569005f41a8d21ca235857fef0fb
  Running setup.py bdist_wheel for django-tagging ... done
  Stored in directory:
/home/pi/.cache/pip/wheels/55/6a/48/46852f206ca8b65fa6cf973e6b9f731ce1d021cbafb279997c
  Running setup.py bdist_wheel for django-sendfile ... done
  Stored in directory:
/home/pi/.cache/pip/wheels/42/54/1c/33af1681da4e9a3dcd8a52dddf08723027ae4fe7892e15646c
  Running setup.py bdist_wheel for MySQL-python ... done
  Stored in directory:
/home/pi/.cache/pip/wheels/38/a3/89/ec87e092cfb38450fc91a62562055231deb0049a029054dc62
  Running setup.py bdist_wheel for lxml ... done
  Stored in directory:
/home/pi/.cache/pip/wheels/ab/61/f2/413c1a5cd899ec8d50e38f0f6196c99d7ae56f094d0575e8bf
Successfully built Django django-tagging django-sendfile MySQL-python
lxml
Installing collected packages: Django, django-tagging, Unidecode,
django-sendfile, MySQL-python, lxml, django-taggit
Successfully installed Django-1.4.5 MySQL-python-1.2.5
Unidecode-0.4.21 django-sendfile-0.3.6 django-tagging-0.3.1
django-taggit-0.14.0 lxml-3.4.4
(penv) pi@pi-7:~/pathagar $ 


### The solution, should this happen again,
# is to run the `pip-error.sh` script.
